
format = """
┌─ $directory
│  ${custom.git_root}${custom.git_branch}$git_metrics$git_status$mise${env_var.MISE_ENV}$all\
└─ $character
"""

[fill]
symbol = "─"

[directory]
format = '[  $path]($style)[$read_only]($read_only_style) '
truncation_length = 5
truncate_to_repo = false

[git_metrics]
disabled = false

[env_var.MISE_ENV]
style = "bold #FFBF00 "
format = "[$symbol$env_value]($style) "

[mise]
disabled = false
healthy_symbol = " "
unhealthy_symbol = "󰗖 "
symbol = ""
style = "bold #FFBF00 "

[custom.git_root]
# it's very slow when running on fish
shell = ["sh"]
# get git repo root directory
command = "git rev-parse --git-common-dir | xargs -n1 realpath | xargs -n1 dirname | xargs -n1 basename"
when = true
require_repo = true
symbol = " "
format = "[$symbol ($output)]($style) "
style = "bold #ff8866"

[custom.git_branch]
description = "A basic version of the git_branch module that doesn't show on bare repos"
# it's very slow when running on fish
shell = ["sh"]
require_repo = true
# don't show on bare repos
when = '''if [[ $(git rev-parse --is-bare-repository) = "true" ]]; then exit 1; else exit 0; fi'''
command = "git rev-parse --abbrev-ref HEAD"
format = 'on [$symbol$output]($style) '
symbol = ' '
style = 'bold purple'

[custom.npm_version]
# this seems to align with the node module automatically
shell = "sh"
command = """version=$(npm --version) && echo v$version"""
require_repo = true
# use the same trigger as nodejs
detect_folders = ['node_modules']
style = "red"
symbol = " "

# ------------------------------------------------------------------------------
# disabled modules
# ------------------------------------------------------------------------------
[package]
disabled = true

[git_branch]
disabled = true
