
format = """
$fill
${env_var.MISE_ENV}$mise$all\
$directory
$character
"""

[fill]
symbol = "─"

[git_metrics]
disabled = false

[env_var.MISE_ENV]
style = "bold #FFBF00 "
format = "[$symbol$env_value]($style) "

[mise]
disabled = false
healthy_symbol = " "
unhealthy_symbol = "󰗖 "
symbol = ""
style = "bold #FFBF00 "
