[tools]
# editor
neovim = "latest"      # "asdf:neovim" = "ref:nightly" 
tree-sitter = "latest"

# dev experience
bat = "latest"
fzf = "latest"
starship = "latest"
zellij = "latest"
zoxide = "latest"

# data scrubbing
ripgrep = "latest"
fd = "latest"
jq = "latest"
gron = "latest"

# git utils
delta = "latest"
lazygit = "latest"
"cargo:sem-cli" = "latest"
jj = "latest"

# llm
opencode = "latest"

# shell
"npm:fish-lsp" = "latest"
