[tools]
# golang
go = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"

# web
node = "lts"
bun = "latest"
"npm:tsc" = "latest"
"npm:vscode-langservers-extracted" = "latest"  # html/json/css/etc language server
"npm:@biomejs/biome" = "latest"  # ts linter and formatter
"npm:@fsouza/prettierd" = "latest"  # formatter for many other files (may consider eslint_d too)

# rust
rust = { version = "latest", components = "rust-analyzer" }
sccache = "latest"

# lua
lua = "latest"
stylua = "latest"
lua-language-server = "latest"

# toml
tombi = "latest"

# yamll
"npm:yaml-language-server" = "latest"

# protobuf
"aqua:coder3101/protols" = "latest"

# python
"pipx:basedpyright" = "latest"
ruff = "latest"

# shell
shfmt = "latest"
shellcheck = "latest"

[env]
# disable go's internal toolchain installer
GOTOOLCHAIN = "local"
RUSTC_WRAPPER = "sccache"
